### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by xarvh** [xarvh/elm-gamepad#35]
The remap tool is giving instruction to the user in English, which severely limit the tool's accessibility.

A simple way to address this would be to add a `remapViewWithLanguage` function that allows to specify a alternate text content for each of the remap messages.

**Comment by mdevlamynck** [comment]
Hi! I'd like to take a jab at this. I can also add the french translation.

**Comment by xarvh** [comment]
Yes please. =)
