### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by xarvh** [xarvh/elm-gamepad#43]
Since there isn't an official way of previewing docs before publishing, I tested the links on https://elm-doc-preview.netlify.com/ which apparently interprets them differently than elm-package.

This is not going to get fixed until there will be a way to test links before publishing.

**Comment by rlefevre** [comment]
Please open a bug at https://github.com/dmy/elm-doc-preview/issues or give me an example of a link that is interpreted differently than elm-package. I am not aware of such an issue and would like elm-doc-preview to behave exactly like the official site.

Thank you!

**Comment by rlefevre** [comment]
I guess you were using a link like `<a href="/Gamepad.Simple>` that works in the preview but not in the final documentation. To avoid using an absolute link like `https://package.elm-lang.org/packages/xarvh/elm-gamepad/latest/Gamepad.Simple` that won't work in the preview or if the official site changes its URL scheme, you could have used `<a href="Gamepad.Simple>` (or `<a href="Gamepad.Simple#Symbol`).

See https://github.com/dmy/elm-doc-preview/issues/9, I will try to add a warning in the preview for such links.

**Comment by xarvh** [comment]
I went again through all the links in the [package page](https://package.elm-lang.org/packages/xarvh/elm-gamepad/latest/) and now they all work, without me having changed anything.
I assume it was an issue with packages.elm-lang.org

Still, thank you for your interest @rlefevre, I wouldn't have checked again hadn't been for your comments.

Closing, as I cannot reproduce it.
