### ISSUE TITLE
PS4 triggers

### ISSUE THREAD

**Issue by brandly** [xarvh/elm-gamepad#50]
looking at [the advanced example](https://xarvh.github.io/elm-gamepad/examples/advanced/#%5B%5D), the "Left Trigger / Left Analog Lever" flips to True when i pull the trigger on the controller. however, "Left Trigger (analog)" stays at 0.

if i pull the right trigger on the controller, **both "Right Trigger (analog)" and "Left Trigger (analog)" show the value from the right trigger**.

(lots left to do, but i think i'll get this integrated into [a game](https://github.com/brandly/elm-rocket-league). thanks!)

**Comment by xarvh** [comment]
It was a problem in the example code, should be fixed now.

Thanks for the heads up, and looking forward to playing your game! =D

**Comment by brandly** [comment]
thanks for the quick fix! i'll let you know once i have gamepad support
